version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      QUEUE_CONNECTION: database
    networks:
      - app-network
    depends_on:
      - mysql

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: always
    volumes:
      - .:/var/www/html
    command: php artisan queue:work database --sleep=3 --tries=3
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      QUEUE_CONNECTION: database
    networks:
      - app-network
    depends_on:
      - mysql
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
